name: AdvancedAchievements-LuckPerms-Hook
description: A middleman plugin to listen for AdvancedAchievements and LuckPerms events and coordinate between the two
version: 2.0.0
authors: [simpleauthority]
depend: [AdvancedAchievements, LuckPerms]
main: com.algorithmjunkie.mc.aalphook.AALPPlugin